# coding: utf-8

"""
    Ostrom API

    The Ostrom API is designed to allow our customer and partners to develop apps that integrates with our smart energy management platform. The API has a RESTful architecture and utilizes OAuth2 authorization.   # noqa: E501

    OpenAPI spec version: 2023-11-01T00:00:00.000Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PricesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_spot_prices(self, start_date, end_date, resolution, **kwargs):  # noqa: E501
        """Retrieve day-ahead spot price information  # noqa: E501

        Allowed role: `USER` or `PARTNER`  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_spot_prices(start_date, end_date, resolution, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object start_date: start date ISO format on UTC timezone. e.g. 2023-11-01T00:00:00.000Z (required)
        :param object end_date: end date ISO format on UTC timezone. e.g. 2023-11-02T00:00:00.000Z (required)
        :param object resolution: The unit of time the data will be aggregated (required)
        :param object zip: Zip code used to fetch Ostrom base price, gridFees, tax and levies. If not provided the respective values are returned as zero.
        :return: GetSpotPriceResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_spot_prices_with_http_info(start_date, end_date, resolution, **kwargs)  # noqa: E501
        else:
            (data) = self.get_spot_prices_with_http_info(start_date, end_date, resolution, **kwargs)  # noqa: E501
            return data

    def get_spot_prices_with_http_info(self, start_date, end_date, resolution, **kwargs):  # noqa: E501
        """Retrieve day-ahead spot price information  # noqa: E501

        Allowed role: `USER` or `PARTNER`  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_spot_prices_with_http_info(start_date, end_date, resolution, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object start_date: start date ISO format on UTC timezone. e.g. 2023-11-01T00:00:00.000Z (required)
        :param object end_date: end date ISO format on UTC timezone. e.g. 2023-11-02T00:00:00.000Z (required)
        :param object resolution: The unit of time the data will be aggregated (required)
        :param object zip: Zip code used to fetch Ostrom base price, gridFees, tax and levies. If not provided the respective values are returned as zero.
        :return: GetSpotPriceResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['start_date', 'end_date', 'resolution', 'zip']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_spot_prices" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'start_date' is set
        if ('start_date' not in params or
                params['start_date'] is None):
            raise ValueError("Missing the required parameter `start_date` when calling `get_spot_prices`")  # noqa: E501
        # verify the required parameter 'end_date' is set
        if ('end_date' not in params or
                params['end_date'] is None):
            raise ValueError("Missing the required parameter `end_date` when calling `get_spot_prices`")  # noqa: E501
        # verify the required parameter 'resolution' is set
        if ('resolution' not in params or
                params['resolution'] is None):
            raise ValueError("Missing the required parameter `resolution` when calling `get_spot_prices`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'start_date' in params:
            query_params.append(('startDate', params['start_date']))  # noqa: E501
        if 'end_date' in params:
            query_params.append(('endDate', params['end_date']))  # noqa: E501
        if 'resolution' in params:
            query_params.append(('resolution', params['resolution']))  # noqa: E501
        if 'zip' in params:
            query_params.append(('zip', params['zip']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ClientAccessToken']  # noqa: E501

        return self.api_client.call_api(
            '/spot-prices', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetSpotPriceResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
