# coding: utf-8

"""
    Ostrom API

    The Ostrom API is designed to allow our customer and partners to develop apps that integrates with our smart energy management platform. The API has a RESTful architecture and utilizes OAuth2 authorization.   # noqa: E501

    OpenAPI spec version: 2023-11-01T00:00:00.000Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ProductsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_product_prices(self, zip, **kwargs):  # noqa: E501
        """Retrieve product prices  # noqa: E501

        Allowed role: `PARTNER`  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_product_prices(zip, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object zip: The postal code where the tariff will be calculated (required)
        :param object number_of_residents: The number of people in the household, if not provided the default value will be 1
        :param object yearly_consumption: The amount of yearly consumption of the household, if not provided the default value will be 1400 kWh
        :return: GetProductPriceResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_product_prices_with_http_info(zip, **kwargs)  # noqa: E501
        else:
            (data) = self.get_product_prices_with_http_info(zip, **kwargs)  # noqa: E501
            return data

    def get_product_prices_with_http_info(self, zip, **kwargs):  # noqa: E501
        """Retrieve product prices  # noqa: E501

        Allowed role: `PARTNER`  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_product_prices_with_http_info(zip, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object zip: The postal code where the tariff will be calculated (required)
        :param object number_of_residents: The number of people in the household, if not provided the default value will be 1
        :param object yearly_consumption: The amount of yearly consumption of the household, if not provided the default value will be 1400 kWh
        :return: GetProductPriceResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['zip', 'number_of_residents', 'yearly_consumption']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_product_prices" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'zip' is set
        if ('zip' not in params or
                params['zip'] is None):
            raise ValueError("Missing the required parameter `zip` when calling `get_product_prices`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'zip' in params:
            query_params.append(('zip', params['zip']))  # noqa: E501
        if 'number_of_residents' in params:
            query_params.append(('numberOfResidents', params['number_of_residents']))  # noqa: E501
        if 'yearly_consumption' in params:
            query_params.append(('yearlyConsumption', params['yearly_consumption']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ClientAccessToken']  # noqa: E501

        return self.api_client.call_api(
            '/products', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetProductPriceResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
