# coding: utf-8

"""
    Ostrom API

    The Ostrom API is designed to allow our customer and partners to develop apps that integrates with our smart energy management platform. The API has a RESTful architecture and utilizes OAuth2 authorization.   # noqa: E501

    OpenAPI spec version: 2023-11-01T00:00:00.000Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contracts_api import ContractsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContractsApi(unittest.TestCase):
    """ContractsApi unit test stubs"""

    def setUp(self):
        self.api = ContractsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_contract_by_external_user_id(self):
        """Test case for get_contract_by_external_user_id

        Retrieve user contract information by external user id  # noqa: E501
        """
        pass

    def test_get_contract_energy_consumption(self):
        """Test case for get_contract_energy_consumption

        Retrieve user contract smart meter consumption  # noqa: E501
        """
        pass

    def test_get_contract_energy_consumption_by_external_user_id(self):
        """Test case for get_contract_energy_consumption_by_external_user_id

        Retrieve user contract smart meter consumption by external user id  # noqa: E501
        """
        pass

    def test_get_contracts(self):
        """Test case for get_contracts

        Retrieve user contracts information  # noqa: E501
        """
        pass

    def test_get_contracts_by_external_user_id(self):
        """Test case for get_contracts_by_external_user_id

        Retrieve user contracts information by external user id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
