# coding: utf-8

"""
    Ostrom API

    The Ostrom API is designed to allow our customer and partners to develop apps that integrates with our smart energy management platform. The API has a RESTful architecture and utilizes OAuth2 authorization.   # noqa: E501

    OpenAPI spec version: 2023-11-01T00:00:00.000Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.o_auth2_token_error400 import OAuth2TokenError400  # noqa: E501
from swagger_client.rest import ApiException


class TestOAuth2TokenError400(unittest.TestCase):
    """OAuth2TokenError400 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuth2TokenError400(self):
        """Test OAuth2TokenError400"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.o_auth2_token_error400.OAuth2TokenError400()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
