# coding: utf-8

"""
    Ostrom API

    The Ostrom API is designed to allow our customer and partners to develop apps that integrates with our smart energy management platform. The API has a RESTful architecture and utilizes OAuth2 authorization.   # noqa: E501

    OpenAPI spec version: 2023-11-01T00:00:00.000Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.orders_api import OrdersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_order_by_external_user_id(self):
        """Test case for get_order_by_external_user_id

        Retrieve user order information by external user id  # noqa: E501
        """
        pass

    def test_get_orders_by_external_user_id(self):
        """Test case for get_orders_by_external_user_id

        Retrieve user orders information by external user id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
