# coding: utf-8

"""
    Ostrom API

    The Ostrom API is designed to allow our customer and partners to develop apps that integrates with our smart energy management platform. The API has a RESTful architecture and utilizes OAuth2 authorization.   # noqa: E501

    OpenAPI spec version: 2023-11-01T00:00:00.000Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_spot_price_item_response import GetSpotPriceItemResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetSpotPriceItemResponse(unittest.TestCase):
    """GetSpotPriceItemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSpotPriceItemResponse(self):
        """Test GetSpotPriceItemResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_spot_price_item_response.GetSpotPriceItemResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
