# coding: utf-8

"""
    Ostrom API

    The Ostrom API is designed to allow our customer and partners to develop apps that integrates with our smart energy management platform. The API has a RESTful architecture and utilizes OAuth2 authorization.   # noqa: E501

    OpenAPI spec version: 2023-11-01T00:00:00.000Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetMeResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'object',
        'first_name': 'object',
        'last_name': 'object',
        'language': 'object'
    }

    attribute_map = {
        'email': 'email',
        'first_name': 'firstName',
        'last_name': 'lastName',
        'language': 'language'
    }

    def __init__(self, email=None, first_name=None, last_name=None, language=None):  # noqa: E501
        """GetMeResponse - a model defined in Swagger"""  # noqa: E501
        self._email = None
        self._first_name = None
        self._last_name = None
        self._language = None
        self.discriminator = None
        if email is not None:
            self.email = email
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if language is not None:
            self.language = language

    @property
    def email(self):
        """Gets the email of this GetMeResponse.  # noqa: E501

        The email address of the user  # noqa: E501

        :return: The email of this GetMeResponse.  # noqa: E501
        :rtype: object
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this GetMeResponse.

        The email address of the user  # noqa: E501

        :param email: The email of this GetMeResponse.  # noqa: E501
        :type: object
        """

        self._email = email

    @property
    def first_name(self):
        """Gets the first_name of this GetMeResponse.  # noqa: E501

        The first name of the user  # noqa: E501

        :return: The first_name of this GetMeResponse.  # noqa: E501
        :rtype: object
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this GetMeResponse.

        The first name of the user  # noqa: E501

        :param first_name: The first_name of this GetMeResponse.  # noqa: E501
        :type: object
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this GetMeResponse.  # noqa: E501

        The last name of the user  # noqa: E501

        :return: The last_name of this GetMeResponse.  # noqa: E501
        :rtype: object
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this GetMeResponse.

        The last name of the user  # noqa: E501

        :param last_name: The last_name of this GetMeResponse.  # noqa: E501
        :type: object
        """

        self._last_name = last_name

    @property
    def language(self):
        """Gets the language of this GetMeResponse.  # noqa: E501

        The language of the user  # noqa: E501

        :return: The language of this GetMeResponse.  # noqa: E501
        :rtype: object
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this GetMeResponse.

        The language of the user  # noqa: E501

        :param language: The language of this GetMeResponse.  # noqa: E501
        :type: object
        """

        self._language = language

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetMeResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetMeResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
