# coding: utf-8

"""
    Ostrom API

    The Ostrom API is designed to allow our customer and partners to develop apps that integrates with our smart energy management platform. The API has a RESTful architecture and utilizes OAuth2 authorization.   # noqa: E501

    OpenAPI spec version: 2023-11-01T00:00:00.000Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WebhooksBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'object',
        'secret': 'object'
    }

    attribute_map = {
        'url': 'url',
        'secret': 'secret'
    }

    def __init__(self, url=None, secret=None):  # noqa: E501
        """WebhooksBody - a model defined in Swagger"""  # noqa: E501
        self._url = None
        self._secret = None
        self.discriminator = None
        if url is not None:
            self.url = url
        if secret is not None:
            self.secret = secret

    @property
    def url(self):
        """Gets the url of this WebhooksBody.  # noqa: E501

        The url of the webhook  # noqa: E501

        :return: The url of this WebhooksBody.  # noqa: E501
        :rtype: object
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this WebhooksBody.

        The url of the webhook  # noqa: E501

        :param url: The url of this WebhooksBody.  # noqa: E501
        :type: object
        """

        self._url = url

    @property
    def secret(self):
        """Gets the secret of this WebhooksBody.  # noqa: E501

        The secret of the webhook  # noqa: E501

        :return: The secret of this WebhooksBody.  # noqa: E501
        :rtype: object
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this WebhooksBody.

        The secret of the webhook  # noqa: E501

        :param secret: The secret of this WebhooksBody.  # noqa: E501
        :type: object
        """

        self._secret = secret

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebhooksBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebhooksBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
