# coding: utf-8

"""
    Ostrom API

    The Ostrom API is designed to allow our customer and partners to develop apps that integrates with our smart energy management platform. The API has a RESTful architecture and utilizes OAuth2 authorization.   # noqa: E501

    OpenAPI spec version: 2023-11-01T00:00:00.000Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetContractsAddressResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'zip': 'object',
        'city': 'object',
        'street': 'object',
        'house_number': 'object'
    }

    attribute_map = {
        'zip': 'zip',
        'city': 'city',
        'street': 'street',
        'house_number': 'houseNumber'
    }

    def __init__(self, zip=None, city=None, street=None, house_number=None):  # noqa: E501
        """GetContractsAddressResponse - a model defined in Swagger"""  # noqa: E501
        self._zip = None
        self._city = None
        self._street = None
        self._house_number = None
        self.discriminator = None
        if zip is not None:
            self.zip = zip
        if city is not None:
            self.city = city
        if street is not None:
            self.street = street
        if house_number is not None:
            self.house_number = house_number

    @property
    def zip(self):
        """Gets the zip of this GetContractsAddressResponse.  # noqa: E501

        The zip code of the address  # noqa: E501

        :return: The zip of this GetContractsAddressResponse.  # noqa: E501
        :rtype: object
        """
        return self._zip

    @zip.setter
    def zip(self, zip):
        """Sets the zip of this GetContractsAddressResponse.

        The zip code of the address  # noqa: E501

        :param zip: The zip of this GetContractsAddressResponse.  # noqa: E501
        :type: object
        """

        self._zip = zip

    @property
    def city(self):
        """Gets the city of this GetContractsAddressResponse.  # noqa: E501

        The city of the address  # noqa: E501

        :return: The city of this GetContractsAddressResponse.  # noqa: E501
        :rtype: object
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this GetContractsAddressResponse.

        The city of the address  # noqa: E501

        :param city: The city of this GetContractsAddressResponse.  # noqa: E501
        :type: object
        """

        self._city = city

    @property
    def street(self):
        """Gets the street of this GetContractsAddressResponse.  # noqa: E501

        The street of the address  # noqa: E501

        :return: The street of this GetContractsAddressResponse.  # noqa: E501
        :rtype: object
        """
        return self._street

    @street.setter
    def street(self, street):
        """Sets the street of this GetContractsAddressResponse.

        The street of the address  # noqa: E501

        :param street: The street of this GetContractsAddressResponse.  # noqa: E501
        :type: object
        """

        self._street = street

    @property
    def house_number(self):
        """Gets the house_number of this GetContractsAddressResponse.  # noqa: E501

        The house number of the address  # noqa: E501

        :return: The house_number of this GetContractsAddressResponse.  # noqa: E501
        :rtype: object
        """
        return self._house_number

    @house_number.setter
    def house_number(self, house_number):
        """Sets the house_number of this GetContractsAddressResponse.

        The house number of the address  # noqa: E501

        :param house_number: The house_number of this GetContractsAddressResponse.  # noqa: E501
        :type: object
        """

        self._house_number = house_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetContractsAddressResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetContractsAddressResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
